# Generated by Django 5.2.7 on 2025-10-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('radius', models.FloatField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('orbital_period', models.FloatField(blank=True, null=True)),
                ('eccentricity', models.FloatField(blank=True, null=True)),
                ('insolation', models.FloatField(blank=True, null=True)),
                ('star_temp', models.IntegerField(blank=True, null=True)),
                ('star_spectral_type', models.CharField(blank=True, max_length=20)),
                ('discovery_method', models.CharField(blank=True, max_length=100)),
                ('discovery_year', models.IntegerField(blank=True, null=True)),
                ('discovery_facility', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
