# Generated by Django 5.2.7 on 2025-10-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='host_star',
            field=models.CharField(default='', max_length=100),
        ),
    ]
