# Generated by Django 5.2.7 on 2025-10-04 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(default='Common', max_length=20)),
                ('attack_power', models.IntegerField(default=10)),
                ('defense_power', models.IntegerField(default=10)),
                ('planet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='planets.planet')),
            ],
        ),
    ]
